#!/usr/bin/env python3
"""stress_test.py — Simulates 50 concurrent quiz participants.

Usage:
    python scripts/stress_test.py https://your-app.onrender.com [--threads 50] [--duration 60]

Requirements:
    pip install requests
    credentials.csv must exist (generated by generate_credentials.py)

The script reads the first N rows from credentials.csv,
then spawns one thread per credential. Each thread:
  1. POST  /login             (authenticate, get JWT)
  2. GET   /api/questions     (load questions)
  3. Every 10 s: POST /save-progress with random answers
  4. After --duration seconds: POST /submit

Prints a summary with avg/max response time, error count, and success rate.
"""

import argparse
import csv
import json
import os
import random
import string
import sys
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path


# ── CLI args ────────────────────────────────────────────────────────────────

def _parse_args():
    p = argparse.ArgumentParser(description="Math Quiz stress tester")
    p.add_argument("base_url", help="Base URL, e.g. https://myapp.onrender.com")
    p.add_argument("--threads",  type=int, default=50, help="Concurrent users (default 50)")
    p.add_argument("--duration", type=int, default=60, help="Seconds before submitting (default 60)")
    p.add_argument("--csv",      default="credentials.csv", help="Path to credentials CSV")
    return p.parse_args()


# ── Stats collector (thread-safe) ────────────────────────────────────────────

@dataclass
class Stats:
    lock:           threading.Lock = field(default_factory=threading.Lock)
    response_times: list           = field(default_factory=list)
    errors:         list           = field(default_factory=list)
    successes:      int            = 0
    failures:       int            = 0

    def record(self, elapsed: float) -> None:
        with self.lock:
            self.response_times.append(elapsed)

    def log_error(self, thread_id: str, phase: str, status: int, body: str) -> None:
        with self.lock:
            self.errors.append({"thread": thread_id, "phase": phase, "status": status, "body": body[:200]})

    def success(self) -> None:
        with self.lock:
            self.successes += 1

    def failure(self) -> None:
        with self.lock:
            self.failures += 1


# ── HTTP helper ──────────────────────────────────────────────────────────────

def _request(method: str, url: str, stats: Stats, phase: str,
             thread_id: str, headers: dict | None = None,
             json_body: dict | None = None):
    """Make an HTTP request, record timing, track errors."""
    import urllib.request
    import urllib.error

    headers = headers or {"Content-Type": "application/json"}
    data    = json.dumps(json_body).encode() if json_body else None

    req = urllib.request.Request(url, data=data, headers=headers, method=method.upper())
    t0  = time.monotonic()

    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            elapsed = time.monotonic() - t0
            stats.record(elapsed)
            body = resp.read().decode("utf-8", errors="replace")
            return resp.status, json.loads(body)
    except urllib.error.HTTPError as exc:
        elapsed = time.monotonic() - t0
        stats.record(elapsed)
        body = exc.read().decode("utf-8", errors="replace")
        stats.log_error(thread_id, phase, exc.code, body)
        return exc.code, {}
    except Exception as exc:
        elapsed = time.monotonic() - t0
        stats.record(elapsed)
        stats.log_error(thread_id, phase, 0, str(exc))
        return 0, {}


# ── Participant simulation ────────────────────────────────────────────────────

def _run_participant(idx: int, base_url: str, team_id: str, pin: str,
                     duration: int, stats: Stats) -> None:
    """Simulate one participant's full quiz session."""
    thread_id = f"T{idx:03d}({team_id})"
    base = base_url.rstrip("/")

    # 1. Login
    status, data = _request(
        "POST", f"{base}/login", stats, "login", thread_id,
        json_body={"team_id": team_id, "pin": pin},
    )
    if status != 200 or "token" not in data:
        print(f"  [FAIL] {thread_id} login failed (HTTP {status})")
        stats.failure()
        return

    token = data["token"]
    auth  = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {token}",
    }

    # 2. Load questions
    status, data = _request("GET", f"{base}/api/questions", stats, "questions", thread_id, auth)
    if status != 200:
        print(f"  [FAIL] {thread_id} questions failed (HTTP {status})")
        stats.failure()
        return

    questions = data.get("questions", [])
    q_ids     = [str(q["question_id"]) for q in questions]

    # 3. Simulate answering + periodic saves
    answers   = {}
    labels    = ["A", "B", "C", "D"]
    start_t   = time.monotonic()
    last_save = start_t

    # Pre-fill some random answers
    for qid in q_ids[:random.randint(10, len(q_ids))]:
        answers[qid] = random.choice(labels)

    while (time.monotonic() - start_t) < duration:
        now = time.monotonic()

        # Answer one more question randomly
        unanswered = [qid for qid in q_ids if qid not in answers]
        if unanswered:
            answers[random.choice(unanswered)] = random.choice(labels)

        # Save every 10 s
        if now - last_save >= 10:
            s_status, _ = _request(
                "POST", f"{base}/save-progress", stats, "save", thread_id,
                auth, json_body={"answers": answers},
            )
            if s_status != 200:
                stats.log_error(thread_id, "save", s_status, "")
            last_save = now

        time.sleep(1)

    # 4. Submit
    status, data = _request("POST", f"{base}/submit", stats, "submit", thread_id, auth)
    if status == 200:
        score = data.get("score", "?")
        print(f"  [OK]   {thread_id} submitted → score {score}/30")
        stats.success()
    else:
        print(f"  [FAIL] {thread_id} submit failed (HTTP {status})")
        stats.failure()


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    args = _parse_args()

    # Load credentials
    csv_path = Path(args.csv)
    if not csv_path.exists():
        print(f"ERROR: credentials CSV not found at {csv_path}")
        sys.exit(1)

    credentials = []
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            credentials.append((row["team_id"], row["pin"]))
            if len(credentials) >= args.threads:
                break

    if not credentials:
        print("ERROR: credentials.csv is empty")
        sys.exit(1)

    n = min(args.threads, len(credentials))
    print(f"\n{'='*60}")
    print(f"Math Quiz Stress Test")
    print(f"  URL:      {args.base_url}")
    print(f"  Threads:  {n}")
    print(f"  Duration: {args.duration}s per participant")
    print(f"  CSV:      {csv_path} ({len(credentials)} credentials loaded)")
    print(f"{'='*60}\n")

    stats   = Stats()
    threads = []
    overall_start = time.monotonic()

    for i, (tid, pin) in enumerate(credentials[:n]):
        t = threading.Thread(
            target=_run_participant,
            args=(i, args.base_url, tid, pin, args.duration, stats),
            daemon=True,
        )
        threads.append(t)

    # Stagger launch slightly to avoid thundering herd on login
    for t in threads:
        t.start()
        time.sleep(0.05)

    for t in threads:
        t.join(timeout=args.duration + 60)

    elapsed_total = time.monotonic() - overall_start

    # ── Summary ───────────────────────────────────────────────────────
    rts   = stats.response_times
    avg   = (sum(rts) / len(rts)) if rts else 0
    mx    = max(rts) if rts else 0
    mn    = min(rts) if rts else 0

    total_attempted = stats.successes + stats.failures
    success_rate    = (stats.successes / total_attempted * 100) if total_attempted else 0

    print(f"\n{'='*60}")
    print(f"RESULTS")
    print(f"{'='*60}")
    print(f"  Total time:      {elapsed_total:.1f}s")
    print(f"  Requests made:   {len(rts)}")
    print(f"  Avg resp time:   {avg*1000:.0f}ms")
    print(f"  Max resp time:   {mx*1000:.0f}ms")
    print(f"  Min resp time:   {mn*1000:.0f}ms")
    print(f"  Successes:       {stats.successes}")
    print(f"  Failures:        {stats.failures}")
    print(f"  Success rate:    {success_rate:.1f}%")
    print(f"  Error count:     {len(stats.errors)}")

    if stats.errors:
        print(f"\n  First 5 errors:")
        for err in stats.errors[:5]:
            print(f"    [{err['phase']}] {err['thread']} HTTP {err['status']}: {err['body']}")

    if success_rate >= 95:
        print(f"\n✓ Stress test PASSED ({success_rate:.1f}% success rate)")
    else:
        print(f"\n✗ Stress test FAILED ({success_rate:.1f}% success rate — target ≥ 95%)")

    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
